# Generated by Django 5.0.2 on 2024-02-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
